### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by gansm** [wimstockman/receipt_demo#1]
Hi Wim,

Three weeks ago, [you asked me](https://github.com/gansm/finalcut/issues/4#issuecomment-1350783078) if I wanted to give you feedback on your new terminal application created with FINAL CUT. I'm glad I finally have the opportunity to do this.

Overall, I think it's fantastic that you were able to implement the application using FINAL CUT. Here are a few suggestions on how you could improve it:

1.    To pass the focus to the next visible widget, you can add the `onFocusIn()` event method to your `RLine` widget class. Because the class `RLine` is not visible, it should include the following code:

```cpp
    void onFocusIn (FFocusEvent* in_ev) override
    {
      // Sets the focus to a child widget if it exists
    
      if ( ! hasChildren() )
        FWidget::onFocusIn(in_ev);
    
      if ( in_ev->getFocusType() == FocusTypes::NextWidget )
      {
        focusFirstChild() ? in_ev->accept() : in_ev->ignore();
      }
      else if ( in_ev->getFocusType() == FocusTypes::PreviousWidget )
      {
        focusLastChild() ? in_ev->accept() : in_ev->ignore();
      }
    }
```

You should also call the `focusNextChild()` function in the overloaded `onChildFocusOut()` event method to allow the user to tab through the entire form.

2.    Currently, you use static sizes for the layout, which assumes that the terminal is a specific size. If you want to create a more flexible widget layout, you can read the section about [dynamic layout](https://github.com/gansm/finalcut/wiki/First-steps#dynamic-layout) in the documentation to implement your own `adjustSize()` method.

3.   To improve the appearance of the terminal, you should change the default font from "Ubuntu Mono Regular 14" to "DejaVu Sans Mono Book 12". That ensures that the arrows fit correctly into a drawing cell. To do this, run the following command in a terminal:

```bash
$ gsettings set org.gnome.desktop.interface monospace-font-name "DejaVu Sans Mono 12"
```

![grafik](https://user-images.githubusercontent.com/12223838/211009705-51a72463-f739-4c7a-bde5-b371624db4d9.png)

![grafik](https://user-images.githubusercontent.com/12223838/211009742-bbc08008-ee78-44a8-8303-4a8c31dbc430.png)

I hope these suggestions are helpful. Keep up the great work, and have fun coding!

Best regards,

Markus

**Comment by wimstockman** [comment]
Hi Markus,

Thanks for all the effort to look at the code.
I implemented the onFocusIn and rewrote the onChildFocusOut.
Also when only adding the OnFocusIn method I noticed that I could not get out of the ScrollView by tabbing.
It always brought me back to the first RLine.
I managed to solve this problem by overriding the focusNextChild() method and detect when the last RLine was and then calling his parent again and refocusing on it.
This looks like I'm making it to complicated:
```
auto focusNextChild() -> bool
	{
		if ( isDialogWidget() || ! hasParent() ) return false;
		const auto& parent = getParentWidget();
		if ( ! parent || ! parent->hasChildren() || parent->numOfFocusableChildren() < 1 ) return false;
		FWidget* next = nullptr;
		constexpr auto ft = FocusTypes::NextWidget;
		auto iter = searchForwardForWidget(parent, this);
		auto iter_of_this_widget = iter;
		do  // Search the next focusable widget
			{
			++iter;
			if ( iter == parent->cend() )
				{
				iter = parent->cbegin();
				const auto& grandparent = parent->getParentWidget();
				parent->setFocus();
				grandparent->focusNextChild();
				return parent ? parent->setFocus(true,ft) : false;
				}
			if ( (*iter)->isWidget() ) next = static_cast<FWidget*>(*iter);
		} while ( iter != iter_of_this_widget && canReceiveFocus(next) );
		// Change focus to the next widget and return true if successful
		return next ? next->setFocus (true, ft) : false;
		}

```


For the dynamic layout part.
Almost everything works fine.
Except inside the Scrollview the RLines do get weird when resizing or moving.
Probably I need to clear the Scrollview somewhere.
Here is a picture.
![dynamic1](https://user-images.githubusercontent.com/5656539/211566599-2ec0cb98-50bb-4732-acc9-221462d3824e.png)

After Scrolling I get this ...
![dynamic2](https://user-images.githubusercontent.com/5656539/211566687-ef44aa46-f3da-48a5-a6da-54f5cd880bf4.png)


For the font remark.
I'm on Artix Linux with dwm and St and font mononoki nerd font 14.
For todays screenshots I took them with xterm that's a smaller font and the arrows are indeed better.

Thanks for all the hard work you put in.

Kind regards,
Wim

**Comment by wimstockman** [comment]
Hi Markus,
I fixed some dynamic layout issues.
but for some reason my RLines are resizing but not reposition ... something weird..
I must be missing something. because the Column labels they do reposition....
Here is a screenshot
![screenshot](https://user-images.githubusercontent.com/5656539/211788694-aa0c0b91-e3c4-4c22-84c5-f8ebf9a6336c.png)

**Comment by wimstockman** [comment]
Apparently overriding the adjustSize method in a new composition widget isn’t a good choose, overriding the draw method did the trick.
